import fs from "node:fs";
import path from "node:path";
import { luaVersionAtLeast, type LuaVersion } from "../../lua/versions.js";
import { resolveLuaVersion } from "../../utils/lua-version.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";

const LUA_EXTENSIONS = new Set([".lua"]);

const PRINT_RE = /^\s*print\s*\(/;
const EMPTY_FUNCTION_RE = /^\s*(?:local\s+)?function\s+\w+\s*\([^)]*\)\s*$/;
const TODO_STUB_RE = /\b(?:TODO|FIXME|HACK|XXX)\b/i;
const GLOBAL_ASSIGN_RE = /^\s*([A-Za-z_]\w*)\s*=/;
const LOCAL_DECL_RE = /^\s*local\s+/;

const VERSION_FEATURES: Array<{
	minimum: LuaVersion;
	pattern: RegExp;
	rule: string;
	message: string;
	help: string;
}> = [
	{
		minimum: "5.2",
		pattern: /\bgoto\b/,
		rule: "ai-slop/lua-version-goto",
		message: "`goto` requires Lua 5.2 or newer",
		help: "Upgrade the project's Lua target to 5.2+, or refactor to structured control flow.",
	},
	{
		minimum: "5.2",
		pattern: /::\s*\w+\s*::/,
		rule: "ai-slop/lua-version-label",
		message: "goto labels require Lua 5.2 or newer",
		help: "Upgrade the project's Lua target to 5.2+, or remove label/goto syntax.",
	},
	{
		minimum: "5.3",
		pattern: /\/\//,
		rule: "ai-slop/lua-version-integer-division",
		message: "Floor division `//` requires Lua 5.3 or newer",
		help: "Use `math.floor(a / b)` on older Lua targets, or raise the project's Lua version.",
	},
	{
		minimum: "5.3",
		pattern: /[&|^~]|<<|>>/,
		rule: "ai-slop/lua-version-bitwise",
		message: "Bitwise operators require Lua 5.3 or newer",
		help: "Use the `bit32` library on Lua 5.2, or upgrade the project's Lua target to 5.3+.",
	},
	{
		minimum: "5.4",
		pattern: /\bconst\s+/,
		rule: "ai-slop/lua-version-const",
		message: "`const` variables require Lua 5.4 or newer",
		help: "Use `local` on older Lua targets, or upgrade the project's Lua version.",
	},
	{
		minimum: "5.4",
		pattern: /<\s*close\s*>/,
		rule: "ai-slop/lua-version-close",
		message: "to-be-closed variables require Lua 5.4 or newer",
		help: "Use explicit cleanup calls on older Lua targets, or upgrade to Lua 5.4+.",
	},
	{
		minimum: "5.5",
		pattern: /\bdeclare\b/,
		rule: "ai-slop/lua-version-declare",
		message: "Global `declare` requires Lua 5.5 or newer",
		help: "Use explicit `local` declarations on older Lua targets, or upgrade to Lua 5.5.",
	},
];

const isTestFile = (relPath: string, basename: string): boolean =>
	basename.startsWith("test_") ||
	basename.endsWith("_test.lua") ||
	basename.endsWith("_spec.lua") ||
	relPath.split(path.sep).some((seg) => seg === "spec" || seg === "tests" || seg === "test");

const isScriptEntrypoint = (basename: string): boolean =>
	basename === "main.lua" || basename === "init.lua" || basename === "cli.lua";

const flag = (
	relPath: string,
	rule: string,
	severity: "warning" | "error" | "info",
	message: string,
	help: string,
	line: number,
): Diagnostic => ({
	filePath: relPath,
	engine: "ai-slop",
	rule,
	severity,
	message,
	help,
	line,
	column: 1,
	category: "AI Slop",
	fixable: false,
});

const detectVersionMismatches = (
	lines: string[],
	relPath: string,
	target: LuaVersion,
	out: Diagnostic[],
): void => {
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		for (const feature of VERSION_FEATURES) {
			if (luaVersionAtLeast(target, feature.minimum)) continue;
			feature.pattern.lastIndex = 0;
			if (!feature.pattern.test(line)) continue;
			out.push(flag(relPath, feature.rule, "warning", feature.message, feature.help, i + 1));
		}
	}
};

interface LineRule {
	pattern: RegExp;
	rule: string;
	severity: "warning" | "error" | "info";
	message: string;
	help: string;
}

const pushLineMatches = (
	lines: string[],
	relPath: string,
	out: Diagnostic[],
	rules: LineRule[],
): void => {
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		for (const entry of rules) {
			entry.pattern.lastIndex = 0;
			if (!entry.pattern.test(line)) continue;
			out.push(flag(relPath, entry.rule, entry.severity, entry.message, entry.help, i + 1));
		}
	}
};

const detectPrintDebug = (
	lines: string[],
	relPath: string,
	basename: string,
	out: Diagnostic[],
): void => {
	if (isScriptEntrypoint(basename)) return;
	pushLineMatches(lines, relPath, out, [
		{
			pattern: PRINT_RE,
			rule: "ai-slop/lua-print-debug",
			severity: "warning",
			message: "print() left in code",
			help: "Use a proper logger or remove debug output before committing.",
		},
	]);
};

const detectEmptyFunctions = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length - 1; i++) {
		if (!EMPTY_FUNCTION_RE.test(lines[i])) continue;
		const next = lines[i + 1].trim();
		if (next !== "end" && next !== "end,") continue;
		out.push(
			flag(
				relPath,
				"ai-slop/empty-function",
				"warning",
				"Empty function body",
				"Implement the function or remove the stub.",
				i + 1,
			),
		);
	}
};

const detectTodoStubs = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	pushLineMatches(lines, relPath, out, [
		{
			pattern: TODO_STUB_RE,
			rule: "ai-slop/todo-stub",
			severity: "info",
			message: "Unresolved TODO/FIXME marker",
			help: "Resolve the marker or track it in an issue tracker instead of leaving it in code.",
		},
	]);
};

const detectGlobalPollution = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (LOCAL_DECL_RE.test(line)) continue;
		const match = GLOBAL_ASSIGN_RE.exec(line);
		if (!match) continue;
		const name = match[1];
		if (name === "return" || name === "function") continue;
		out.push(
			flag(
				relPath,
				"ai-slop/lua-global-assign",
				"warning",
				`Global assignment to \`${name}\``,
				"Prefer `local` variables to avoid polluting the global namespace.",
				i + 1,
			),
		);
	}
};

export const detectLuaPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const targetVersion = resolveLuaVersion(context.rootDirectory);
	const files = getSourceFiles(context);

	for (const filePath of files) {
		if (!LUA_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		const relPath = path.relative(context.rootDirectory, filePath);
		const basename = path.basename(filePath);
		if (isTestFile(relPath, basename)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const lines = content.split("\n");
		detectVersionMismatches(lines, relPath, targetVersion, diagnostics);
		detectPrintDebug(lines, relPath, basename, diagnostics);
		detectEmptyFunctions(lines, relPath, diagnostics);
		detectTodoStubs(lines, relPath, diagnostics);
		detectGlobalPollution(lines, relPath, diagnostics);
	}

	return diagnostics;
};
