import fs from "node:fs";
import path from "node:path";
import type { LuaVersion } from "../../lua/versions.js";
import { resolveLuaVersion } from "../../utils/lua-version.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { Diagnostic, EngineContext } from "../types.js";
import { stripLineComment } from "./lua-version-rule-fixes.js";
import {
	LUA_VERSION_MISMATCH_RULES,
	shouldFlagVersionRule,
	type LuaVersionMismatchRule,
} from "./lua-version-rules.js";

const LUA_EXTENSIONS = new Set([".lua"]);

const PRINT_RE = /^\s*print\s*\(/;
const EMPTY_FUNCTION_RE = /^\s*(?:local\s+)?function\s+\w+\s*\([^)]*\)\s*$/;
const TODO_STUB_RE = /\b(?:TODO|FIXME|HACK|XXX)\b/i;
const GLOBAL_ASSIGN_RE = /^\s*([A-Za-z_]\w*)\s*=/;
const LOCAL_DECL_RE = /^\s*local\s+/;

const isTestFile = (relPath: string, basename: string): boolean =>
	basename.startsWith("test_") ||
	basename.endsWith("_test.lua") ||
	basename.endsWith("_spec.lua") ||
	relPath.split(path.sep).some((seg) => seg === "spec" || seg === "tests" || seg === "test");

const isScriptEntrypoint = (basename: string): boolean =>
	basename === "main.lua" || basename === "init.lua" || basename === "cli.lua";

const flag = (relPath: string, rule: LuaVersionMismatchRule, line: number): Diagnostic => ({
	filePath: relPath,
	engine: "ai-slop",
	rule: rule.rule,
	severity: "warning",
	message: rule.message,
	help: rule.help,
	line,
	column: 1,
	category: "AI Slop",
	fixable: rule.fixable,
});

const detectVersionMismatches = (
	lines: string[],
	relPath: string,
	target: LuaVersion,
	out: Diagnostic[],
): void => {
	for (let i = 0; i < lines.length; i++) {
		const line = stripLineComment(lines[i]);
		for (const rule of LUA_VERSION_MISMATCH_RULES) {
			if (!shouldFlagVersionRule(rule, target)) continue;
			rule.pattern.lastIndex = 0;
			if (!rule.pattern.test(line)) continue;
			out.push(flag(relPath, rule, i + 1));
		}
	}
};

interface LineRule {
	pattern: RegExp;
	rule: string;
	severity: "warning" | "error" | "info";
	message: string;
	help: string;
	fixable?: boolean;
}

const pushLineMatches = (
	lines: string[],
	relPath: string,
	out: Diagnostic[],
	rules: LineRule[],
): void => {
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		for (const entry of rules) {
			entry.pattern.lastIndex = 0;
			if (!entry.pattern.test(line)) continue;
			out.push({
				filePath: relPath,
				engine: "ai-slop",
				rule: entry.rule,
				severity: entry.severity,
				message: entry.message,
				help: entry.help,
				line: i + 1,
				column: 1,
				category: "AI Slop",
				fixable: entry.fixable ?? false,
			});
		}
	}
};

const detectPrintDebug = (
	lines: string[],
	relPath: string,
	basename: string,
	out: Diagnostic[],
): void => {
	if (isScriptEntrypoint(basename)) return;
	pushLineMatches(lines, relPath, out, [
		{
			pattern: PRINT_RE,
			rule: "ai-slop/lua-print-debug",
			severity: "warning",
			message: "print() left in code",
			help: "Use a proper logger or remove debug output before committing.",
		},
	]);
};

const detectEmptyFunctions = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length - 1; i++) {
		if (!EMPTY_FUNCTION_RE.test(lines[i])) continue;
		const next = lines[i + 1].trim();
		if (next !== "end" && next !== "end,") continue;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/empty-function",
			severity: "warning",
			message: "Empty function body",
			help: "Implement the function or remove the stub.",
			line: i + 1,
			column: 1,
			category: "AI Slop",
			fixable: false,
		});
	}
};

const detectTodoStubs = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	pushLineMatches(lines, relPath, out, [
		{
			pattern: TODO_STUB_RE,
			rule: "ai-slop/todo-stub",
			severity: "info",
			message: "Unresolved TODO/FIXME marker",
			help: "Resolve the marker or track it in an issue tracker instead of leaving it in code.",
		},
	]);
};

const detectGlobalPollution = (lines: string[], relPath: string, out: Diagnostic[]): void => {
	for (let i = 0; i < lines.length; i++) {
		const line = lines[i];
		if (LOCAL_DECL_RE.test(line)) continue;
		const match = GLOBAL_ASSIGN_RE.exec(line);
		if (!match) continue;
		const name = match[1];
		if (name === "return" || name === "function") continue;
		out.push({
			filePath: relPath,
			engine: "ai-slop",
			rule: "ai-slop/lua-global-assign",
			severity: "warning",
			message: `Global assignment to \`${name}\``,
			help: "Prefix with `local` to keep the variable scoped to the file.",
			line: i + 1,
			column: 1,
			category: "AI Slop",
			fixable: true,
		});
	}
};

export const detectLuaPatterns = async (context: EngineContext): Promise<Diagnostic[]> => {
	const diagnostics: Diagnostic[] = [];
	const targetVersion = resolveLuaVersion(context.rootDirectory);
	const files = getSourceFiles(context);

	for (const filePath of files) {
		if (!LUA_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		const relPath = path.relative(context.rootDirectory, filePath);
		const basename = path.basename(filePath);
		if (isTestFile(relPath, basename)) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const lines = content.split("\n");
		detectVersionMismatches(lines, relPath, targetVersion, diagnostics);
		detectPrintDebug(lines, relPath, basename, diagnostics);
		detectEmptyFunctions(lines, relPath, diagnostics);
		detectTodoStubs(lines, relPath, diagnostics);
		detectGlobalPollution(lines, relPath, diagnostics);
	}

	return diagnostics;
};
