import fs from "node:fs";
import path from "node:path";
import type { LuaVersion } from "../../lua/versions.js";
import { resolveLuaVersion } from "../../utils/lua-version.js";
import { getSourceFiles, isAutoGenerated } from "../../utils/source-files.js";
import type { EngineContext } from "../types.js";
import {
	LUA_VERSION_MISMATCH_RULES,
	shouldFlagVersionRule,
	type LuaVersionMismatchRule,
} from "./lua-version-rules.js";

const LUA_EXTENSIONS = new Set([".lua"]);

const isTestFile = (relPath: string, basename: string): boolean =>
	basename.startsWith("test_") ||
	basename.endsWith("_test.lua") ||
	basename.endsWith("_spec.lua") ||
	relPath.split(path.sep).some((seg) => seg === "spec" || seg === "tests" || seg === "test");

const fixableRulesForTarget = (
	target: ReturnType<typeof resolveLuaVersion>,
): LuaVersionMismatchRule[] =>
	LUA_VERSION_MISMATCH_RULES.filter(
		(rule) => rule.fixable && rule.fixLine && shouldFlagVersionRule(rule, target),
	);

const applyLineFixes = (
	lines: string[],
	rules: LuaVersionMismatchRule[],
	target: LuaVersion,
): string[] => {
	const next = [...lines];
	let changed = false;

	for (let i = 0; i < next.length; i++) {
		let line = next[i];
		for (const rule of rules) {
			if (!rule.fixLine) continue;
			const fixed = rule.fixLine(line, target);
			if (!fixed || fixed === line) continue;
			line = fixed;
			changed = true;
		}
		next[i] = line;
	}

	return changed ? next : lines;
};

const fixGlobalAssignments = (lines: string[]): string[] => {
	const next = [...lines];
	let changed = false;
	for (let i = 0; i < next.length; i++) {
		const line = next[i];
		if (/^\s*local\s+/.test(line)) continue;
		const match = line.match(/^(\s*)([A-Za-z_]\w*)\s*=/);
		if (!match) continue;
		const name = match[2];
		if (name === "return" || name === "function") continue;
		next[i] = line.replace(/^(\s*)([A-Za-z_]\w*)\s*=/, "$1local $2 =");
		changed = true;
	}
	return changed ? next : lines;
};

export const fixLuaPatterns = async (context: EngineContext): Promise<void> => {
	await fixLuaVersionMismatches(context);
	await fixLuaGlobalAssignments(context);
};

const fixLuaGlobalAssignments = async (context: EngineContext): Promise<void> => {
	const files = getSourceFiles(context);
	for (const filePath of files) {
		if (!LUA_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		const relPath = path.relative(context.rootDirectory, filePath);
		if (isTestFile(relPath, path.basename(filePath))) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const lines = content.split("\n");
		const fixed = fixGlobalAssignments(lines);
		if (fixed === lines) continue;
		fs.writeFileSync(filePath, fixed.join("\n"));
	}
};

const fixLuaVersionMismatches = async (context: EngineContext): Promise<void> => {
	const target = resolveLuaVersion(context.rootDirectory);
	const rules = fixableRulesForTarget(target);
	if (rules.length === 0) return;

	const files = getSourceFiles(context);
	for (const filePath of files) {
		if (!LUA_EXTENSIONS.has(path.extname(filePath))) continue;
		if (isAutoGenerated(filePath)) continue;

		const relPath = path.relative(context.rootDirectory, filePath);
		if (isTestFile(relPath, path.basename(filePath))) continue;

		let content: string;
		try {
			content = fs.readFileSync(filePath, "utf-8");
		} catch {
			continue;
		}

		const lines = content.split("\n");
		const fixedLines = applyLineFixes(lines, rules, target);
		if (fixedLines === lines) continue;

		// Re-run fixes until stable (e.g. multiple operators on one line).
		let current = fixedLines;
		for (let pass = 0; pass < 4; pass++) {
			const updated = applyLineFixes(current, rules, target);
			if (updated === current) break;
			current = updated;
		}

		fs.writeFileSync(filePath, current.join("\n"));
	}
};
