/** Lua-related ai-slop rule ids for the rules catalog and fixable set. */
export const LUA_AI_SLOP_FIXABLE_RULES = [
	"ai-slop/lua-global-assign",
	"ai-slop/lua-version-integer-division",
	"ai-slop/lua-version-bitwise",
	"ai-slop/lua-version-const",
	"ai-slop/lua-version-close",
	"ai-slop/lua-version-warn",
	"ai-slop/lua-version-declare",
	"ai-slop/lua-version-table-unpack",
	"ai-slop/lua-version-loadstring",
	"ai-slop/lua-version-bit32",
	"ai-slop/lua-version-unpack-global",
	"ai-slop/lua-version-math-atan2",
	"ai-slop/lua-version-math-pow",
	"ai-slop/lua-version-math-mod",
	"ai-slop/lua-version-gfind",
	"ai-slop/lua-version-table-getn",
	"ai-slop/lua-version-table-setn",
	"ai-slop/lua-version-package-loaders",
	"ai-slop/lua-version-package-searchers",
	"ai-slop/lua-version-loadlib",
	"ai-slop/lua-version-math-log10",
	"ai-slop/lua-version-math-ldexp",
] as const;

export const LUA_AI_SLOP_BUILTIN_RULES = [
	"ai-slop/lua-print-debug",
	"ai-slop/lua-global-assign",
	"ai-slop/lua-version-goto",
	"ai-slop/lua-version-label",
	"ai-slop/lua-version-integer-division",
	"ai-slop/lua-version-bitwise",
	"ai-slop/lua-version-const",
	"ai-slop/lua-version-close",
	"ai-slop/lua-version-declare",
	"ai-slop/lua-version-warn",
	"ai-slop/lua-version-string-pack",
	"ai-slop/lua-version-utf8",
	"ai-slop/lua-version-table-create",
	"ai-slop/lua-version-table-move",
	"ai-slop/lua-version-table-unpack",
	"ai-slop/lua-version-env",
	"ai-slop/lua-version-len",
	"ai-slop/lua-version-loadstring",
	"ai-slop/lua-version-setfenv",
	"ai-slop/lua-version-getfenv",
	"ai-slop/lua-version-module",
	"ai-slop/lua-version-bit32",
	"ai-slop/lua-version-unpack-global",
	"ai-slop/lua-version-math-atan2",
	"ai-slop/lua-version-math-pow",
	"ai-slop/lua-version-math-mod",
	"ai-slop/lua-version-gfind",
	"ai-slop/lua-version-table-getn",
	"ai-slop/lua-version-table-setn",
	"ai-slop/lua-version-table-maxn",
	"ai-slop/lua-version-table-foreach",
	"ai-slop/lua-version-package-loaders",
	"ai-slop/lua-version-package-searchers",
	"ai-slop/lua-version-table-pack",
	"ai-slop/lua-version-loadlib",
	"ai-slop/lua-version-math-log10",
	"ai-slop/lua-version-math-ldexp",
	"ai-slop/lua-version-math-frexp",
	"ai-slop/lua-version-math-hyperbolic",
	"ai-slop/lua-version-debug-fenv",
] as const;
